# fly.toml app configuration file generated for discentes on 2024-09-23T18:15:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discentes" # Replace <coder-app-name> with the name of your app
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "gru"  # See a list of regions here: https://fly.io/docs/reference/regions/

[experimental]
auto_rollback = true
private_network = true  # Allows Coder to connect to the database

[build]
image = "ghcr.io/coder/coder:latest"

[env]
CODER_ACCESS_URL = "https://discentes.fly.dev" # Replace <app-name> with the name of your app
CODER_HTTP_ADDRESS = "0.0.0.0:3000"
#CODER_VERBOSE = "true" # Uncomment this if you want to see more logs
CODER_TELEMETRY_INSTALL_SOURCE = "fly.io"

[[services]]
protocol = "tcp"
internal_port = 3000
processes = ["app"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 25
